title: UHManoasList
<a id="forkme_banner" href="https://github.com/uhmanoaslist/uhmanoalistcode">View on GitHub</a>
description: A flea market service for the University of Hawaii at Manoa community
theme: jekyll-theme-slate
