title: UHManoasList
github:
repository_url: https://github.com/uhmanoaslist/uhmanoalistcode
description: A flea market service for the University of Hawaii at Manoa community
theme: jekyll-theme-slate
